name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Greet new users
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome! Thanks for opening your first issue. We'll review it soon. If you have questions, let us know."
          pr-message: "Hello! Thanks for your first pull request. We'll review it shortly. If you need help, feel free to ask."
